# This is for ubuntu 20.04 server running in virtual box
# for configuring net access as well as host/whole lan access
# may need virtual boxes dhcp server running
# /etc/netplan/00-installer-config.yaml
network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: true
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
    enps08:
      dhcp4: false
      addresses: [192.168.1.201/24]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.1.1
          metric: 200
